export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const DRAFT_CHANGE = 'DRAFT_CHANGE';
export const ADD_CHAT = 'ADD_CHAT';
export const OPEN_MODAL_ADD_CHAT = 'OPEN_MODAL_ADD_CHAT';